name: Deploy to FTP

on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 3: Upload files to FTP
      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASS }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ${{ secrets.WEB_DIR }}
          state-name: ".ftp-deploy-sync-state.json"  # Tracks changes
          dangerous-clean-slate: false  # Prevents deleting existing files unless tracked